create table
  public.roles_tb (
    id bigint generated by default as identity,
    name character varying null,
    created_at timestamp with time zone not null default now(),
    constraint roles_tb_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.users_tb (
    id bigint generated by default as identity,
    name character varying not null,
    token character varying not null,
    created_at timestamp with time zone not null default now(),
    uuid uuid not null default gen_random_uuid (),
    salt character varying not null,
    email character varying not null,
    constraint users_tb_pkey primary key (id),
    constraint users_tb_id_key unique (id),
    constraint users_tb_name_key unique (name)
  ) tablespace pg_default;

create table
  public.rooms_tb (
    id bigint generated by default as identity,
    room character varying not null,
    created_at timestamp with time zone not null default now(),
    name character varying null,
    constraint rooms_tb_pkey primary key (id),
    constraint rooms_tb_id_key unique (id)
  ) tablespace pg_default;

create table
  public.users_characters_tb (
    id bigint generated by default as identity,
    name text not null,
    room_id bigint not null,
    created_at timestamp with time zone not null default now(),
    user_id bigint not null,
    role_id bigint not null,
    constraint users_characters_tb_pkey primary key (id),
    constraint users_characters_tb_role_id_fkey foreign key (role_id) references roles_tb (id),
    constraint users_characters_tb_room_id_fkey foreign key (room_id) references rooms_tb (id),
    constraint users_characters_tb_user_id_fkey foreign key (user_id) references users_tb (id)
  ) tablespace pg_default;

create table
  public.characters_inventory_tb (
    id bigint generated by default as identity,
    item character varying null,
    quant bigint not null default '1'::bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),
    active boolean not null default true,
    character_id bigint null,
    constraint characters_inventory_tb_pkey primary key (id),
    constraint characters_inventory_tb_item_key unique (item),
    constraint characters_inventory_tb_character_id_fkey foreign key (character_id) references users_characters_tb (id)
  ) tablespace pg_default;

create table
  public.characters_info_tb (
    id bigint generated by default as identity,
    life bigint null,
    notes character varying null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),
    age bigint null,
    character_id bigint not null,
    constraint characters_info_tb_pkey primary key (id),
    constraint characters_info_tb_character_id_fkey foreign key (character_id) references users_characters_tb (id)
  ) tablespace pg_default;